### ISSUE TITLE
inconsistent parameterization of yaf dockerfile

### ISSUE THREAD

**Issue by lapolonio** [jasimpson/Dockerfiles#1]
https://github.com/jasimpson/Dockerfiles/blob/master/yaf-super_mediator-silk/Dockerfile#L28
and
https://github.com/jasimpson/Dockerfiles/blob/master/yaf-super_mediator-silk/Dockerfile#L49

don't use library versions specified at top of dockerfile

**Comment by jasimpson** [comment]
Fixed in #3
